# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

minGPUs: 4
parallelism:
  default:
    tp: 1
    pp: 1
  b200:
    tp: 1
    pp: 1
  h100:
    tp: 2
    pp: 1
  a100:
    tp: 8
    pp: 1
  l40s:
    tp: 4
    pp: 1
  l40:
    tp: 4
    pp: 1
  rtxpro6000:
    tp: 4
    pp: 1
